### ISSUE TITLE
Calibration example

### ISSUE THREAD

**Issue by Mattsw23** [CalPlug/ADE9078-3PhaseWattmeter#1]
Hello,

I'm making a simple ade9078 board with esp32 I would like to use to read voltages and amps over time. I don't know if I'm wrong but this example rise lot of error on compiling.  
first compiler run: 
1)  'EEPROM' was not declared in this scope at line 203 so added EEPROM.h include and bypassed this.  
2)  no matching function for call to 'ADE9078::ADE9078()' at line 291. I commented it and new error
3)'class ADE9078' has no member named 'writeWordToEeprom'.  ( this refer to ade9000 API??)

I'm little confused....    ade9000 which I previously used has i2c EEPROM and the ade9000 example use i2c to write to internal chip EEPROM.  I understand in your code you write directly to esp32 EEPROM to save data but looking at error 3 seems that you're referring to ade9000 api.  
Can I ask you help about ? just to specify I defined the ESP32 architecture in .h

thanks Matt

**Comment by mjklopfer** [comment]
right, this is getting fixed....  The final updates have not been pushed - this is an extension of the ADE9000 firmware example to the ADE9078

**Comment by mjklopfer** [comment]
This chipset does not use UART/I2C, it is SPI only.  CRC function implemented and other garbage cleaned out, WFB is known working, direct calibration example (basic functionality that will need to be application adjusted) will be present in: https://github.com/CalPlug/ArduinoMenuCalibrator

For WFB on 3 phases an Arduino Uno cannot keep up with required memory, an ESP32 has been tested and is known working for this application.
